### ISSUE TITLE
After last update RtcDateTime now = Rtc.GetDateTime().Epoch32Time() return error for conversion from uint32_t

### ISSUE THREAD

**Issue by fabrimp** [Makuna/Rtc#161]
Hi Makuna,

Thank you so much for your work on this library.

I would like to report that after the last update, I'm having the following issue when trying to get the epoch time using RtcDateTime now = Rtc.GetDateTime().Epoch32Time()

Compilation error: conversion from 'uint32_t {aka unsigned int}' to non-scalar type 'RtcDateTime' requested"

If I roll back the library to the previous version it works without any issues.

I'm really sorry if this change was intended it is not a real issue. Please let me know if there is another fix for this besides restoring to a previous version.

I'm using this code on an esp32 on arduino ide 2.0.3 if you need any further information please let me know.

Kind Regards

**Comment by Makuna** [comment]
Covered in [this discussion](https://github.com/Makuna/Rtc/discussions/160).

This line is incorrect, it is causing bugs in peoples sketches so I make sure the new changes would no longer allow it.
```
RtcDateTime now = Rtc.GetDateTime().Epoch32Time();
```
`now` was being constructed with the wrong time value, it takes a seconds from 2000/1/1.  Epoch32Time is seconds since 1970/1/1.  

this is all you need
```
RtcDateTime now = Rtc.GetDateTime();
```
