### ISSUE TITLE
Alarm and SQW Pin output

### ISSUE THREAD

**Issue by m1ch3l4** [Makuna/Rtc#79]
Hello, I'm using the library together with NodeMCU - Esp8266E.

Set date, time and alarm easily. And when the alarm goes off the SQW goes from HIGH to LOW - okay.

I need the SQW to trigger when the alarm is triggered - press HIGH to LOW and HIGH again.

I'm looking in the library for the method responsible for the alarm action, but I can not find it.

I also tried SetSquareWavePinClockFrequency set to 1Hz but it did not work as I expected.

What do you recommend?

**Comment by Makuna** [comment]
Please follow the guidelines for creating issues.  This is not a place to ask questions, this is where active bugs in the  library are registered.  The Wiki and Readme point toward the Gitter channel for asking questions and you will get faster responce times.

Which RTC hardware are you working with? Alarms are not available on all the devices.
DS3231, look at the example DS3241_Alarms.ino
DS3234, look at the example DS3234_Alarms.ino


Closing due to just being a question.
